"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import { handleThemeConfiguration } from "./utils/handleTheme";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col w-full h-full gap-20`}>
        <div className="fixed w-full h-14 bg-gray-surfaceVariantBrighter flex gap-10 justify-end px-20 items-center">
          <button
            className="bg-gray-onSurfaceVariantBrighter text-gray-surfaceVariantBrighter rounded-md  px-4 py-2 flex justify-center items-center"
            onClick={() => handleThemeConfiguration("dark")}
          >
            Dark
          </button>
          <button
            className="bg-gray-onSurfaceVariantBrighter text-gray-surfaceVariantBrighter rounded-md  px-4 py-2 flex justify-center items-center"
            onClick={() => handleThemeConfiguration("light")}
          >
            Light
          </button>
        </div>
        <div className="h-full w-full fixed mt-14 flex justify-center bg-gray-surfaceVariant items-center">
          {children}
        </div>
      </body>
    </html>
  );
}
