import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import Header from "./components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col w-full h-full gap-20`}>
        <Header />
        <div className="h-full w-full fixed mt-14 flex justify-center bg-gray-surfaceVariant items-center">
          {children}
        </div>
      </body>
    </html>
  );
}
